In [1]:
import numpy as np
import pandas as pd

In [14]:
data = {
    'name': ['jatin', 'bharteee', 'supriya', 'mayank'],
    'age': [21, 18, 20, 21],
    'city': ['germany', 'spain', 'india', 'USA'],
}
df = pd.DataFrame(data)

In [15]:
df

       name  age     city
0     jatin   21  germany
1  bharteee   18    spain
2   supriya   20    india
3    mayank   21      USA

In [22]:
df[['name', 'age']]

       name  age
0     jatin   21
1  bharteee   18
2   supriya   20
3    mayank   21

In [24]:
df['designation'] = ['engineer', 'lawyer', 'lawyer', 'engineer']

In [25]:
df

       name  age     city designation
0     jatin   21  germany    engineer
1  bharteee   18    spain      lawyer
2   supriya   20    india      lawyer
3    mayank   21      USA    engineer

In [28]:
df.drop('designation',axis = 1,inplace = True)

In [29]:
df

       name  age     city
0     jatin   21  germany
1  bharteee   18    spain
2   supriya   20    india
3    mayank   21      USA

In [30]:
df.drop(3, axis = 0)

       name  age     city
0     jatin   21  germany
1  bharteee   18    spain
2   supriya   20    india

In [31]:
df.loc[0]

name      jatin
age          21
city    germany
Name: 0, dtype: object

In [32]:
df.loc[[0,1]]

       name  age     city
0     jatin   21  germany
1  bharteee   18    spain

In [33]:
df.loc[[0,1]][['name','city']]

       name     city
0     jatin  germany
1  bharteee    spain

In [36]:
df[df['age']>20]

     name  age     city
0   jatin   21  germany
3  mayank   21      USA

In [41]:
df[(df['age']>20) & (df['city'] == 'germany')]

    name  age     city
0  jatin   21  germany