In [1]:
import numpy as np
import pandas as pd

In [5]:
data = {
    "A" : [1, 2, np.nan, 4, 5],
    "B" : [1, 2, 3, 4, 5],
    "C" : [1, 2, 3, np.nan, np.nan],
    "D" : [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)

In [6]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [7]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [8]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [9]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

In [10]:
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [11]:
df.dropna(thresh = 3)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

In [12]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [13]:
df.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [14]:
values = { "A":3, "C":4, "D":5}

In [16]:
df.fillna(value = values)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  5.0
2  3.0  3  3.0  5.0
3  4.0  4  4.0  5.0
4  5.0  5  4.0  5.0

In [17]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0