merging

In [1]:
import numpy as np
import pandas as pd

In [11]:
employees = pd.DataFrame({
    'employee_id' : [1, 2, 3, 4, 5],
    'name' : ['jaitn', 'mayank', 'bhartee', 'shashank','supriya'],
    'Department' : ['IT', 'HR','HR', 'IT', 'HR']
})
salary = pd.DataFrame({
    'employee_id' : [1, 2, 3, 6, 7],
    'salary' : [ 200000, 150000, 200000, 150000,150000],
    'bonus' : [ 20000, 30000, 40000, 20000, 30000]
})

In [12]:
employees

   employee_id      name Department
0            1     jaitn         IT
1            2    mayank         HR
2            3   bhartee         HR
3            4  shashank         IT
4            5   supriya         HR

In [13]:
salary

   employee_id  salary  bonus
0            1  200000  20000
1            2  150000  30000
2            3  200000  40000
3            6  150000  20000
4            7  150000  30000

In [14]:
pd.merge(employees, salary)

   employee_id     name Department  salary  bonus
0            1    jaitn         IT  200000  20000
1            2   mayank         HR  150000  30000
2            3  bhartee         HR  200000  40000

In [15]:
pd.merge(employees, salary, on = 'employee_id', how = 'inner')

   employee_id     name Department  salary  bonus
0            1    jaitn         IT  200000  20000
1            2   mayank         HR  150000  30000
2            3  bhartee         HR  200000  40000

In [16]:
pd.merge(employees, salary, on = 'employee_id', how = 'outer')

   employee_id      name Department    salary    bonus
0            1     jaitn         IT  200000.0  20000.0
1            2    mayank         HR  150000.0  30000.0
2            3   bhartee         HR  200000.0  40000.0
3            4  shashank         IT       NaN      NaN
4            5   supriya         HR       NaN      NaN
5            6       NaN        NaN  150000.0  20000.0
6            7       NaN        NaN  150000.0  30000.0

In [17]:
pd.merge(employees, salary, on = 'employee_id', how = 'left')

   employee_id      name Department    salary    bonus
0            1     jaitn         IT  200000.0  20000.0
1            2    mayank         HR  150000.0  30000.0
2            3   bhartee         HR  200000.0  40000.0
3            4  shashank         IT       NaN      NaN
4            5   supriya         HR       NaN      NaN

In [18]:
pd.merge(employees, salary, on = 'employee_id', how = 'right')

   employee_id     name Department  salary  bonus
0            1    jaitn         IT  200000  20000
1            2   mayank         HR  150000  30000
2            3  bhartee         HR  200000  40000
3            6      NaN        NaN  150000  20000
4            7      NaN        NaN  150000  30000

CONCATINATION

In [27]:
df1 = pd.DataFrame({
    'A' : [ 'A0', 'A1', 'A2'],
    'B' : [ 'B0', 'B1', 'B2'],
    'C' : [ 'C1', 'C2', 'C3']
})

df2 = pd.DataFrame({
    'A' : [ 'A3', 'A4', 'A5'],
    'B' : [ 'B3', 'B4', 'B5'],
    'C' : [ 'C3', 'C4', 'C5']
})

In [28]:
df1

    A   B   C
0  A0  B0  C1
1  A1  B1  C2
2  A2  B2  C3

In [29]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [31]:
pd.concat([df1, df2])

    A   B   C
0  A0  B0  C1
1  A1  B1  C2
2  A2  B2  C3
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [32]:
pd.concat([df1, df2], axis = 0)

    A   B   C
0  A0  B0  C1
1  A1  B1  C2
2  A2  B2  C3
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [33]:
pd.concat([df1, df2], axis = 1)

    A   B   C   A   B   C
0  A0  B0  C1  A3  B3  C3
1  A1  B1  C2  A4  B4  C4
2  A2  B2  C3  A5  B5  C5

JOINING

In [46]:
df1 = pd.DataFrame({
    'name': ['jatin', 'mayank', 'bhartee', 'supriya']
},index = [1, 2, 3, 4])
df2 = pd.DataFrame({
    'score': [ 99, 98, 97, 96]
}, index = [2, 3, 4, 5])

In [47]:
df1

      name
1    jatin
2   mayank
3  bhartee
4  supriya

In [48]:
df2

   score
2     99
3     98
4     97
5     96

In [49]:
df1.join(df2, how = 'inner')

      name  score
2   mayank     99
3  bhartee     98
4  supriya     97

In [50]:
df1.join(df2, how = 'outer')

      name  score
1    jatin    NaN
2   mayank   99.0
3  bhartee   98.0
4  supriya   97.0
5      NaN   96.0

In [51]:
df1.join(df2)

      name  score
1    jatin    NaN
2   mayank   99.0
3  bhartee   98.0
4  supriya   97.0